use crate::cpu::AddressingMode;

#[derive(Copy, Clone)]
pub enum Instruction {
    Adc,
    And,
    Asl,
    Bcc,
    Bcs,
    Beq,
    Bit,
    Bmi,
    Bne,
    Bpl,
    Bra,
    Brk,
    Brl,
    Bvc,
    Bvs,
    Clc,
    Cld,
    Cli,
    Clv,
    Cmp,
    Cop,
    Cpx,
    Cpy,
    Dec,
    Dex,
    Dey,
    Eor,
    Inc,
    Inx,
    Iny,
    Jml,
    Jmp,
    Jsl,
    Jsr,
    Lda,
    Ldx,
    Ldy,
    Lsr,
    Mvn,
    Mvp,
    Nop,
    Ora,
    Pea,
    Pei,
    Per,
    Pha,
    Phb,
    Phd,
    Phk,
    Php,
    Phx,
    Phy,
    Pla,
    Plb,
    Pld,
    Plp,
    Plx,
    Ply,
    Rep,
    Rol,
    Ror,
    Rti,
    Rtl,
    Rts,
    Sbc,
    Sep,
    Sec,
    Sed,
    Sei,
    Sta,
    Stp,
    Stx,
    Sty,
    Stz,
    Tax,
    Tay,
    Txy,
    Tyx,
    Tcd,
    Tcs,
    Tdc,
    Trb,
    Tsb,
    Tsc,
    Tsx,
    Txa,
    Txs,
    Tya,
    Wai,
    Wdm,
    Xba,
    Xce,
    Hcf(u8) // Reserved for errors
}


impl Instruction {
    pub fn as_str(self) -> &'static str {
        match self {
            Instruction::Adc => "ADC",
            Instruction::And => "AND",
            Instruction::Asl => "ASL",
            Instruction::Bcc => "BCC",
            Instruction::Bcs => "BCS",
            Instruction::Beq => "BEQ",
            Instruction::Bit => "BIT",
            Instruction::Bmi => "BMI",
            Instruction::Bne => "BNE",
            Instruction::Bpl => "BPL",
            Instruction::Bra => "BRA",
            Instruction::Brk => "BRK",
            Instruction::Brl => "BRL",
            Instruction::Bvc => "BVC",
            Instruction::Bvs => "BVS",
            Instruction::Clc => "CLC",
            Instruction::Cld => "CLD",
            Instruction::Cli => "CLI",
            Instruction::Clv => "CLV",
            Instruction::Cmp => "CMP",
            Instruction::Cop => "COP",
            Instruction::Cpx => "CPX",
            Instruction::Cpy => "CPY",
            Instruction::Dec => "DEC",
            Instruction::Dex => "DEX",
            Instruction::Dey => "DEY",
            Instruction::Eor => "EOR",
            Instruction::Inc => "INC",
            Instruction::Inx => "INX",
            Instruction::Iny => "INY",
            Instruction::Jml => "JML",
            Instruction::Jmp => "JMP",
            Instruction::Jsl => "JSL",
            Instruction::Jsr => "JSR",
            Instruction::Lda => "LDA",
            Instruction::Ldx => "LDX",
            Instruction::Ldy => "LDY",
            Instruction::Lsr => "LSR",
            Instruction::Mvn => "MVN",
            Instruction::Mvp => "MVP",
            Instruction::Nop => "NOP",
            Instruction::Ora => "ORA",
            Instruction::Pea => "PEA",
            Instruction::Pei => "PEI",
            Instruction::Per => "PER",
            Instruction::Pha => "PHA",
            Instruction::Phb => "PHB",
            Instruction::Phd => "PHD",
            Instruction::Phk => "PHK",
            Instruction::Php => "PHP",
            Instruction::Phx => "PHX",
            Instruction::Phy => "PHY",
            Instruction::Pla => "PLA",
            Instruction::Plb => "PLB",
            Instruction::Pld => "PLD",
            Instruction::Plp => "PLP",
            Instruction::Plx => "PLX",
            Instruction::Ply => "PLY",
            Instruction::Rep => "REP",
            Instruction::Rol => "ROL",
            Instruction::Ror => "ROR",
            Instruction::Rti => "RTI",
            Instruction::Rtl => "RTL",
            Instruction::Rts => "RTS",
            Instruction::Sbc => "SBC",
            Instruction::Sep => "SEP",
            Instruction::Sec => "SEC",
            Instruction::Sed => "SED",
            Instruction::Sei => "SEI",
            Instruction::Sta => "STA",
            Instruction::Stp => "STP",
            Instruction::Stx => "STX",
            Instruction::Sty => "STY",
            Instruction::Stz => "STZ",
            Instruction::Tax => "TAX",
            Instruction::Tay => "TAY",
            Instruction::Txy => "TXY",
            Instruction::Tyx => "TYX",
            Instruction::Tcd => "TCD",
            Instruction::Tcs => "TCS",
            Instruction::Tdc => "TDC",
            Instruction::Trb => "TRB",
            Instruction::Tsb => "TSB",
            Instruction::Tsc => "TSC",
            Instruction::Tsx => "TSX",
            Instruction::Txa => "TXA",
            Instruction::Txs => "TXS",
            Instruction::Tya => "TYA",
            Instruction::Wai => "WAI",
            Instruction::Wdm => "WDM",
            Instruction::Xba => "XBA",
            Instruction::Xce => "XCE",
            Instruction::Hcf(_) => "HCF[Virtual]"
        }
    }

    #[cfg(debug_assertions)]
    pub fn opcodes(&self) -> Vec<u8> {
        MAPPINGS.iter()
                .filter(|(instr,_)| std::mem::discriminant(instr) == std::mem::discriminant(self))
                .map(|(_,code_slice)| code_slice[0])
                .collect()
    }
}

macro_rules! generate_table {
    (
        $(
            $code:expr => ($instr:ident, $mode:ident, $cycles:expr)
        ),* $(,)?
    ) => {
        // Generated by generate_table! macro
        pub const OPCODES: [Opcode; 256] = {
            let mut table = [Opcode { instr: Instruction::Hcf(0), mode: AddressingMode::Implied, cycles: 1 }; 256];
            let mut index = 0;
            while index < 256 {
                table[index] = Opcode { instr: Instruction::Hcf(index as u8), mode: AddressingMode::Implied, cycles: 1 };
                index += 1;
            }

            $(
                table[$code] = Opcode {
                    instr: Instruction::$instr,
                    mode: AddressingMode::$mode,
                    cycles: $cycles,
                };
            )*

            table
        };

        #[cfg(debug_assertions)]
        pub const MAPPINGS: &[(Instruction, &[u8])] = &[
            $(
                (Instruction::$instr, &[$code]),
            )*
        ];
    }
}

#[derive(Copy, Clone)]
pub struct Opcode {
    pub instr: Instruction,
    pub mode: AddressingMode,
    pub cycles: u8
}

generate_table!(
    0x00 => (Brk, Stack,               7),
    0x01 => (Ora, DirectIndirectX,     6),
    0x02 => (Cop, Stack,               7),
    0x03 => (Ora, StackRelative,       4),
    0x04 => (Tsb, Direct,              5),
    0x05 => (Ora, Direct,              3),
    0x06 => (Asl, Direct,              5),
    0x07 => (Ora, DirectIndirectLong,  6),
    0x08 => (Php, Stack,               3),
    0x09 => (Ora, ImmediateAcc,        2),
    0x0A => (Asl, Implied,             2),
    0x0B => (Phd, Stack,               4),
    0x0C => (Tsb, Absolute,            6),
    0x0D => (Ora, Absolute,            4),
    0x0E => (Asl, Absolute,            6),
    0x0F => (Ora, AbsoluteLong,        5),
    0x10 => (Bpl, Relative,            2),
    0x11 => (Ora, DirectIndirectY,     5),
    0x12 => (Ora, DirectIndirect,      5),
    0x13 => (Ora, StackRelativeY,      7),
    0x14 => (Trb, Direct,              5),
    0x15 => (Ora, DirectX,             4),
    0x16 => (Asl, DirectX,             6),
    0x17 => (Ora, DirectIndirectLongY, 6),
    0x18 => (Clc, Implied,             2),
    0x19 => (Ora, AbsoluteY,           4),
    0x1A => (Inc, Implied,             2),
    0x1B => (Tcs, Implied,             2),
    0x1C => (Trb, Absolute,            6),
    0x1D => (Ora, AbsoluteX,           4),
    0x1E => (Asl, AbsoluteX,           7),
    0x1F => (Ora, AbsoluteLongX,       5),
    0x20 => (Jsr, Absolute,            6),
    0x21 => (And, DirectIndirectX,     6),
    0x22 => (Jsl, AbsoluteLong,        8),
    0x23 => (And, StackRelative,       4),
    0x24 => (Bit, Direct,              3),
    0x25 => (And, Direct,              3),
    0x26 => (Rol, Direct,              5),
    0x27 => (And, DirectIndirectLong,  6),
    0x28 => (Plp, Stack,               4),
    0x29 => (And, ImmediateAcc,        2),
    0x2A => (Rol, Implied,             2),
    0x2B => (Pld, Stack,               5),
    0x2C => (Bit, Absolute,            4),
    0x2D => (And, Absolute,            4),
    0x2E => (Rol, Absolute,            6),
    0x2F => (And, AbsoluteLong,        5),
    0x30 => (Bmi, Relative,            2),
    0x31 => (And, DirectIndirectX,     5),
    0x32 => (And, DirectIndirect,      5),
    0x33 => (And, StackRelative,       7),
    0x34 => (Bit, DirectX,             4),
    0x35 => (And, DirectX,             4),
    0x36 => (Rol, DirectX,             6),
    0x37 => (And, DirectIndirectLongY, 6),
    0x38 => (Sec, Implied,             2),
    0x39 => (And, AbsoluteY,           4),
    0x3A => (Dec, Implied,             2),
    0x3B => (Tsc, Implied,             2),
    0x3C => (Bit, AbsoluteX,           4),
    0x3D => (And, AbsoluteX,           4),
    0x3E => (Rol, AbsoluteX,           7),
    0x3F => (And, AbsoluteLongX,       5),
    0x40 => (Rti, Stack,               7),
    0x41 => (Eor, DirectIndirectX,     6),
    0x42 => (Wdm, Implied,             2),
    0x43 => (Eor, StackRelative,       4),
    0x44 => (Mvp, BlockMove,           7),
    0x45 => (Eor, Direct,              3),
    0x46 => (Lsr, Direct,              5),
    0x47 => (Eor, DirectIndirectLong,  6),
    0x48 => (Pha, Stack,               3),
    0x49 => (Eor, ImmediateAcc,        2),
    0x4A => (Lsr, Implied,             2),
    0x4B => (Phk, Stack,               3),
    0x4C => (Jmp, Absolute,            3),
    0x4D => (Eor, Absolute,            4),
    0x4E => (Lsr, Absolute,            6),
    0x4F => (Eor, AbsoluteLong,        5),
    0x50 => (Bvc, Relative,            2),
    0x51 => (Eor, DirectIndirectX,     5),
    0x52 => (Eor, DirectIndirect,      5),
    0x53 => (Eor, StackRelativeY,      7),
    0x54 => (Mvn, BlockMove,           7),
    0x55 => (Eor, DirectX,             4),
    0x56 => (Lsr, DirectX,             6),
    0x57 => (Eor, DirectIndirectLongY, 6),
    0x58 => (Cli, Implied,             2),
    0x59 => (Eor, AbsoluteY,           4),
    0x5A => (Phy, Stack,               3),
    0x5B => (Tcd, Implied,             2),
    0x5C => (Jmp, AbsoluteLong,        4),
    0x5D => (Eor, AbsoluteX,           4),
    0x5E => (Lsr, AbsoluteX,           7),
    0x5F => (Eor, AbsoluteLongX,       5),
    0x60 => (Rts, Stack,               6),
    0x61 => (Adc, DirectIndirectX,     6),
    0x62 => (Per, ImmediateWord,       6),
    0x63 => (Adc, StackRelative,       4),
    0x64 => (Stz, Direct,              3),
    0x65 => (Adc, Direct,              3),
    0x66 => (Ror, Direct,              5),
    0x67 => (Adc, DirectIndirectLong,  6),
    0x68 => (Pla, Stack,               4),
    0x69 => (Adc, ImmediateAcc,        2),
    0x6A => (Ror, ImmediateAcc,        2),
    0x6B => (Rtl, Stack,               6),
    0x6C => (Jmp, AbsoluteIndirect,    5),
    0x6D => (Adc, Absolute,            4),
    0x6E => (Ror, Absolute,            6),
    0x6F => (Adc, AbsoluteLong,        5),
    0x70 => (Bvs, Relative,            2),
    0x71 => (Adc, DirectIndirectY,     5),
    0x72 => (Adc, DirectIndirect,      5),
    0x73 => (Adc, StackRelativeY,      7),
    0x74 => (Stz, DirectX,             4),
    0x75 => (Adc, DirectX,             4),
    0x76 => (Ror, DirectX,             6),
    0x77 => (Adc, DirectIndirectLongY, 6),
    0x78 => (Sei, Implied,             2),
    0x79 => (Adc, AbsoluteY,           4),
    0x7A => (Ply, Stack,               4),
    0x7B => (Tdc, Implied,             2),
    0x7C => (Jmp, AbsoluteIndirectX,   6),
    0x7D => (Adc, AbsoluteX,           4),
    0x7E => (Ror, AbsoluteX,           7),
    0x7F => (Adc, AbsoluteLongX,       5),
    0x80 => (Bra, Relative,            2),
    0x81 => (Sta, DirectIndirectX,     6),
    0x82 => (Brl, RelativeLong,        4),
    0x83 => (Sta, StackRelative,       4),
    0x84 => (Sty, Direct,              3),
    0x85 => (Sta, Direct,              3),
    0x86 => (Stx, Direct,              3),
    0x87 => (Sta, DirectIndirectLong,  2),
    0x88 => (Dey, Implied,             2),
    0x89 => (Bit, ImmediateAcc,        2),
    0x8A => (Txa, Implied,             2),
    0x8B => (Phb, Stack,               3),
    0x8C => (Sty, Absolute,            4),
    0x8D => (Sta, Absolute,            4),
    0x8E => (Stx, Absolute,            4),
    0x8F => (Sta, AbsoluteLong,        5),
    0x90 => (Bcc, Relative,            2),
    0x91 => (Sta, DirectIndirectY,     6),
    0x92 => (Sta, DirectIndirect,      5),
    0x93 => (Sta, StackRelativeY,      7),
    0x94 => (Sty, DirectX,             4),
    0x95 => (Sta, DirectX,             4),
    0x96 => (Stx, DirectY,             4),
    0x97 => (Sta, DirectIndirectLongY, 6),
    0x98 => (Tya, Implied,             2),
    0x99 => (Sta, AbsoluteY,           5),
    0x9A => (Txs, Implied,             2),
    0x9B => (Txy, Implied,             2),
    0x9C => (Stz, Absolute,            4),
    0x9D => (Sta, AbsoluteX,           5),
    0x9E => (Stz, AbsoluteX,           5),
    0x9F => (Sta, AbsoluteLongX,       5),
    0xA0 => (Ldy, ImmediateIdx,        2),
    0xA1 => (Lda, DirectIndirectX,     6),
    0xA2 => (Ldx, ImmediateIdx,        2),
    0xA3 => (Lda, StackRelative,       4),
    0xA4 => (Ldy, Direct,              3),
    0xA5 => (Lda, Direct,              3),
    0xA6 => (Ldx, Direct,              3),
    0xA7 => (Lda, DirectIndirectLong,  3),
    0xA8 => (Tay, Implied,             2),
    0xA9 => (Lda, ImmediateAcc,        2),
    0xAA => (Tax, Implied,             2),
    0xAB => (Plb, Stack,               4),
    0xAC => (Ldy, Absolute,            4),
    0xAD => (Lda, Absolute,            4),
    0xAE => (Ldx, Absolute,            4),
    0xAF => (Lda, AbsoluteLong,        5),
    0xB0 => (Bcs, Relative,            2),
    0xB1 => (Lda, DirectIndirectY,     5),
    0xB2 => (Lda, DirectIndirect,      5),
    0xB3 => (Lda, StackRelativeY,      7),
    0xB4 => (Ldy, DirectX,             4),
    0xB5 => (Lda, DirectX,             4),
    0xB6 => (Ldx, DirectY,             4),
    0xB7 => (Lda, DirectIndirectLongY, 6),
    0xB8 => (Clv, Implied,             2),
    0xB9 => (Lda, AbsoluteY,           4),
    0xBA => (Tsx, Implied,             2),
    0xBB => (Tyx, Implied,             2),
    0xBC => (Ldy, AbsoluteX,           4),
    0xBD => (Lda, AbsoluteX,           4),
    0xBE => (Ldx, AbsoluteY,           4),
    0xBF => (Lda, AbsoluteLongX,       5),
    0xC0 => (Cpy, ImmediateIdx,        2),
    0xC1 => (Cmp, DirectIndirectX,     6),
    0xC2 => (Rep, ImmediateByte,       3),
    0xC3 => (Cmp, StackRelative,       4),
    0xC4 => (Cpy, Direct,              3),
    0xC5 => (Cmp, Direct,              3),
    0xC6 => (Dec, Direct,              5),
    0xC7 => (Cmp, DirectIndirectLong,  6),
    0xC8 => (Iny, Implied,             2),
    0xC9 => (Cmp, ImmediateAcc,        2),
    0xCA => (Dex, Implied,             2),
    0xCB => (Wai, Implied,             3),
    0xCC => (Cpy, Absolute,            4),
    0xCD => (Cmp, Absolute,            4),
    0xCE => (Dec, Absolute,            6),
    0xCF => (Cmp, AbsoluteLong,        5),
    0xD0 => (Bne, Relative,            2),
    0xD1 => (Cmp, DirectIndirectY,     5),
    0xD2 => (Cmp, DirectIndirect,      5),
    0xD3 => (Cmp, StackRelativeY,      7),
    0xD4 => (Pei, Direct,               6),
    0xD5 => (Cmp, DirectX,             4),
    0xD6 => (Dec, DirectX,             6),
    0xD7 => (Cmp, DirectIndirectLongY, 6),
    0xD8 => (Cld, Implied,             2),
    0xD9 => (Cmp, AbsoluteY,           4),
    0xDA => (Phx, Stack,               3),
    0xDB => (Stp, Implied,             3),
    0xDC => (Jml, AbsoluteIndirect,    6),
    0xDD => (Cmp, AbsoluteX,           4),
    0xDE => (Dec, AbsoluteX,           7),
    0xDF => (Cmp, AbsoluteLongX,       5),
    0xE0 => (Cpx, ImmediateIdx,        2),
    0xE1 => (Sbc, DirectIndirectX,     6),
    0xE2 => (Sep, ImmediateByte,       3),
    0xE3 => (Sbc, StackRelative,       4),
    0xE4 => (Cpx, Direct,              3),
    0xE5 => (Sbc, Direct,              3),
    0xE6 => (Inc, Direct,              5),
    0xE7 => (Sbc, DirectIndirectLong,  6),
    0xE8 => (Inx, Implied,             2),
    0xE9 => (Sbc, ImmediateAcc,        2),
    0xEA => (Nop, Implied,             2),
    0xEB => (Xba, Implied,             3),
    0xEC => (Cpx, Absolute,            4),
    0xED => (Sbc, Absolute,            4),
    0xEE => (Inc, Absolute,            6),
    0xEF => (Sbc, AbsoluteLong,        5),
    0xF0 => (Beq, Relative,            2),
    0xF1 => (Sbc, DirectIndirectY,     5),
    0xF2 => (Sbc, DirectIndirect,      5),
    0xF3 => (Sbc, StackRelativeY,      7),
    0xF4 => (Pea, ImmediateWord,       5),
    0xF5 => (Sbc, DirectX,             4),
    0xF6 => (Inc, DirectX,             6),
    0xF7 => (Sbc, DirectIndirectLongY, 6),
    0xF8 => (Sed, Implied,             2),
    0xF9 => (Sbc, AbsoluteY,           4),
    0xFA => (Plx, Stack,               4),
    0xFB => (Xce, Implied,             2),
    0xFC => (Jsr, AbsoluteIndirectX,   8),
    0xFD => (Sbc, AbsoluteX,           4),
    0xFE => (Inc, AbsoluteX,           7),
    0xFF => (Sbc, AbsoluteLongX,       5),
);
