#[derive(Copy, Clone)]
pub enum AddressingMode {
//  NAME                    SHORTHAND(S)
    Absolute,            // a
    AbsoluteIndirectX,   // (a,x)
    AbsoluteX,           // a,x
    AbsoluteY,           // a,y
    AbsoluteIndirect,    // (a)
    AbsoluteLongX,       // al,x
    AbsoluteLong,        // al
    BlockMove,           // xyc
    DirectIndirectX,     // (d,x)
    DirectX,             // d,x
    DirectY,             // d,y
    DirectIndirectY,     // (d),y
    DirectIndirectLongY, // [d],y
    DirectIndirectLong,  // [d]
    DirectIndirect,      // (d)
    Direct,              // d
    ImmediateAcc,        // #
    ImmediateIdx,        // #
    ImmediateByte,       // #
    ImmediateWord,       // #
    Implied,             // i
    RelativeLong,        // rl
    Relative,            // r
    Stack,               // s
    StackRelative,       // d,s
    StackRelativeY,      // (d,s),y
}

impl AddressingMode {
    #[cfg(debug_assertions)]
    pub fn as_str(self) -> &'static str {
        match self {
            AddressingMode::Absolute            => "Absolute",
            AddressingMode::AbsoluteIndirectX   => "AbsoluteIndirectX",
            AddressingMode::AbsoluteX           => "AbsoluteX",
            AddressingMode::AbsoluteY           => "AbsoluteY",
            AddressingMode::AbsoluteIndirect    => "AbsoluteIndirect",
            AddressingMode::AbsoluteLongX       => "AbsoluteLongX",
            AddressingMode::AbsoluteLong        => "AbsoluteLong",
            AddressingMode::BlockMove           => "BlockMove",
            AddressingMode::DirectIndirectX     => "DirectIndirectX",
            AddressingMode::DirectX             => "DirectX",
            AddressingMode::DirectY             => "DirectY",
            AddressingMode::DirectIndirectY     => "DirectIndirectY",
            AddressingMode::DirectIndirectLongY => "DirectIndirectLongY",
            AddressingMode::DirectIndirectLong  => "DirectIndirectLong",
            AddressingMode::DirectIndirect      => "DirectIndirect",
            AddressingMode::Direct              => "Direct",
            AddressingMode::ImmediateAcc        => "ImmediateAcc",
            AddressingMode::ImmediateIdx        => "ImmediateIdx",
            AddressingMode::ImmediateByte       => "ImmediateByte",
            AddressingMode::ImmediateWord       => "ImmediateWord",
            AddressingMode::Implied             => "Implied",
            AddressingMode::Stack               => "Stack",
            AddressingMode::RelativeLong        => "RelativeLong",
            AddressingMode::Relative            => "Relative",
            AddressingMode::StackRelative       => "StackRelative",
            AddressingMode::StackRelativeY      => "StackRelativeY",
        }
    }
}

#[derive(Copy, Clone)]
pub enum Instruction {
    ADC,
    AND,
    ASL,
    BCC,
    BCS,
    BEQ,
    BIT,
    BMI,
    BNE,
    BPL,
    BRA,
    BRK,
    BRL,
    BVC,
    BVS,
    CLC,
    CLD,
    CLI,
    CLV,
    CMP,
    COP,
    CPX,
    CPY,
    DEC,
    DEX,
    DEY,
    EOR,
    INC,
    INX,
    INY,
    JML,
    JMP,
    JSL,
    JSR,
    LDA,
    LDX,
    LDY,
    LSR,
    MVN,
    MVP,
    NOP,
    ORA,
    PEA,
    PEI,
    PER,
    PHA,
    PHB,
    PHD,
    PHK,
    PHP,
    PHX,
    PHY,
    PLA,
    PLB,
    PLD,
    PLP,
    PLX,
    PLY,
    REP,
    ROL,
    ROR,
    RTI,
    RTL,
    RTS,
    SBC,
    SEP,
    SEC,
    SED,
    SEI,
    STA,
    STP,
    STX,
    STY,
    STZ,
    TAX,
    TAY,
    TXY,
    TYX,
    TCD,
    TCS,
    TDC,
    TRB,
    TSB,
    TSC,
    TSX,
    TXA,
    TXS,
    TYA,
    WAI,
    WDM,
    XBA,
    XCE,
    HCF(u8) // Reserved for errors
}


impl Instruction {
    pub fn as_str(self) -> &'static str {
        match self {
            Instruction::ADC => "ADC",
            Instruction::AND => "AND",
            Instruction::ASL => "ASL",
            Instruction::BCC => "BCC",
            Instruction::BCS => "BCS",
            Instruction::BEQ => "BEQ",
            Instruction::BIT => "BIT",
            Instruction::BMI => "BMI",
            Instruction::BNE => "BNE",
            Instruction::BPL => "BPL",
            Instruction::BRA => "BRA",
            Instruction::BRK => "BRK",
            Instruction::BRL => "BRL",
            Instruction::BVC => "BVC",
            Instruction::BVS => "BVS",
            Instruction::CLC => "CLC",
            Instruction::CLD => "CLD",
            Instruction::CLI => "CLI",
            Instruction::CLV => "CLV",
            Instruction::CMP => "CMP",
            Instruction::COP => "COP",
            Instruction::CPX => "CPX",
            Instruction::CPY => "CPY",
            Instruction::DEC => "DEC",
            Instruction::DEX => "DEX",
            Instruction::DEY => "DEY",
            Instruction::EOR => "EOR",
            Instruction::INC => "INC",
            Instruction::INX => "INX",
            Instruction::INY => "INY",
            Instruction::JML => "JML",
            Instruction::JMP => "JMP",
            Instruction::JSL => "JSL",
            Instruction::JSR => "JSR",
            Instruction::LDA => "LDA",
            Instruction::LDX => "LDX",
            Instruction::LDY => "LDY",
            Instruction::LSR => "LSR",
            Instruction::MVN => "MVN",
            Instruction::MVP => "MVP",
            Instruction::NOP => "NOP",
            Instruction::ORA => "ORA",
            Instruction::PEA => "PEA",
            Instruction::PEI => "PEI",
            Instruction::PER => "PER",
            Instruction::PHA => "PHA",
            Instruction::PHB => "PHB",
            Instruction::PHD => "PHD",
            Instruction::PHK => "PHK",
            Instruction::PHP => "PHP",
            Instruction::PHX => "PHX",
            Instruction::PHY => "PHY",
            Instruction::PLA => "PLA",
            Instruction::PLB => "PLB",
            Instruction::PLD => "PLD",
            Instruction::PLP => "PLP",
            Instruction::PLX => "PLX",
            Instruction::PLY => "PLY",
            Instruction::REP => "REP",
            Instruction::ROL => "ROL",
            Instruction::ROR => "ROR",
            Instruction::RTI => "RTI",
            Instruction::RTL => "RTL",
            Instruction::RTS => "RTS",
            Instruction::SBC => "SBC",
            Instruction::SEP => "SEP",
            Instruction::SEC => "SEC",
            Instruction::SED => "SED",
            Instruction::SEI => "SEI",
            Instruction::STA => "STA",
            Instruction::STP => "STP",
            Instruction::STX => "STX",
            Instruction::STY => "STY",
            Instruction::STZ => "STZ",
            Instruction::TAX => "TAX",
            Instruction::TAY => "TAY",
            Instruction::TXY => "TXY",
            Instruction::TYX => "TYX",
            Instruction::TCD => "TCD",
            Instruction::TCS => "TCS",
            Instruction::TDC => "TDC",
            Instruction::TRB => "TRB",
            Instruction::TSB => "TSB",
            Instruction::TSC => "TSC",
            Instruction::TSX => "TSX",
            Instruction::TXA => "TXA",
            Instruction::TXS => "TXS",
            Instruction::TYA => "TYA",
            Instruction::WAI => "WAI",
            Instruction::WDM => "WDM",
            Instruction::XBA => "XBA",
            Instruction::XCE => "XCE",
            Instruction::HCF(_) => "HCF[Virtual]"
        }
    }
}

macro_rules! generate_table {
    (
        $(
            $code:expr => ($instr:ident, $mode:ident, $cycles:expr)
        ),* $(,)?
    ) => {{
        let mut table = [Opcode { instr: Instruction::HCF(0), mode: AddressingMode::Implied, cycles: 1 }; 256];
        let mut index = 0;
        while index < 256 {
            table[index] = Opcode { instr: Instruction::HCF(index as u8), mode: AddressingMode::Implied, cycles: 1 };
            index += 1;
        }

        $(
            table[$code] = Opcode {
                instr: Instruction::$instr,
                mode: AddressingMode::$mode,
                cycles: $cycles,
            };
        )*

        table
    }};
}

#[derive(Copy, Clone)]
pub struct Opcode {
    pub instr: Instruction,
    pub mode: AddressingMode,
    pub cycles: u8
}

pub const OPCODES: [Opcode; 256] =
    generate_table!(
        0x00 => (BRK, Stack,               7),
        0x01 => (ORA, DirectIndirectX,     6),
        0x02 => (COP, Stack,               7),
        0x03 => (ORA, StackRelative,       4),
        0x04 => (TSB, Direct,              5),
        0x05 => (ORA, Direct,              3),
        0x06 => (ASL, Direct,              5),
        0x07 => (ORA, DirectIndirectLong,  6),
        0x08 => (PHP, Stack,               3),
        0x09 => (ORA, ImmediateAcc,        2),
        0x0A => (ASL, Implied,             2),
        0x0B => (PHD, Stack,               4),
        0x0C => (TSB, Absolute,            6),
        0x0D => (ORA, Absolute,            4),
        0x0E => (ASL, Absolute,            6),
        0x0F => (ORA, AbsoluteLong,        5),
        0x10 => (BPL, Relative,            2),
        0x11 => (ORA, DirectIndirectY,     5),
        0x12 => (ORA, DirectIndirect,      5),
        0x13 => (ORA, StackRelativeY,      7),
        0x14 => (TRB, Direct,              5),
        0x15 => (ORA, DirectX,             4),
        0x16 => (ASL, DirectX,             6),
        0x17 => (ORA, DirectIndirectLongY, 6),
        0x18 => (CLC, Implied,             2),
        0x19 => (ORA, AbsoluteY,           4),
        0x1A => (INC, Implied,             2),
        0x1B => (TCS, Implied,             2),
        0x1C => (TRB, Absolute,            6),
        0x1D => (ORA, AbsoluteX,           4),
        0x1E => (ASL, AbsoluteX,           7),
        0x1F => (ORA, AbsoluteLongX,       5),
        0x20 => (JSR, Absolute,            6),
        0x21 => (AND, DirectIndirectX,     6),
        0x22 => (JSL, AbsoluteLong,        8),
        0x23 => (AND, StackRelative,       4),
        0x24 => (BIT, Direct,              3),
        0x25 => (AND, Direct,              3),
        0x26 => (ROL, Direct,              5),
        0x27 => (AND, DirectIndirectLong,  6),
        0x28 => (PLP, Stack,               4),
        0x29 => (AND, ImmediateAcc,        2),
        0x2A => (ROL, Implied,             2),
        0x2B => (PLD, Stack,               5),
        0x2C => (BIT, Absolute,            4),
        0x2D => (AND, Absolute,            4),
        0x2E => (ROL, Absolute,            6),
        0x2F => (AND, AbsoluteLong,        5),
        0x30 => (BMI, Relative,            2),
        0x31 => (AND, DirectIndirectX,     5),
        0x32 => (AND, DirectIndirect,      5),
        0x33 => (AND, StackRelative,       7),
        0x34 => (BIT, DirectX,             4),
        0x35 => (AND, DirectX,             4),
        0x36 => (ROL, DirectX,             6),
        0x37 => (AND, DirectIndirectLongY, 6),
        0x38 => (SEC, Implied,             2),
        0x39 => (AND, AbsoluteY,           4),
        0x3A => (DEC, ImmediateAcc,        2),
        0x3B => (TSC, Implied,             2),
        0x3C => (BIT, AbsoluteX,           4),
        0x3D => (AND, AbsoluteX,           4),
        0x3E => (ROL, AbsoluteX,           7),
        0x3F => (AND, AbsoluteLongX,       5),
        0x40 => (RTI, Stack,               7),
        0x41 => (EOR, DirectIndirectX,     6),
        0x42 => (WDM, Implied,             2),
        0x43 => (EOR, StackRelative,       4),
        0x44 => (MVP, BlockMove,           7),
        0x45 => (EOR, Direct,              3),
        0x46 => (LSR, Direct,              5),
        0x47 => (EOR, DirectIndirectLong,  6),
        0x48 => (PHA, Stack,               3),
        0x49 => (EOR, ImmediateAcc,        2),
        0x4A => (LSR, Implied,             2),
        0x4B => (PHK, Stack,               3),
        0x4C => (JMP, Absolute,            3),
        0x4D => (EOR, Absolute,            4),
        0x4E => (LSR, Absolute,            6),
        0x4F => (EOR, AbsoluteLong,        5),
        0x50 => (BVC, Relative,            2),
        0x51 => (EOR, DirectIndirectX,     5),
        0x52 => (EOR, DirectIndirect,      5),
        0x53 => (EOR, StackRelativeY,      7),
        0x54 => (MVN, BlockMove,           7),
        0x55 => (EOR, DirectX,             4),
        0x56 => (LSR, DirectX,             6),
        0x57 => (EOR, DirectIndirectLongY, 6),
        0x58 => (CLI, Implied,             2),
        0x59 => (EOR, AbsoluteY,           4),
        0x5A => (PHY, Stack,               3),
        0x5B => (TCD, Implied,             2),
        0x5C => (JMP, AbsoluteLong,        4),
        0x5D => (EOR, AbsoluteX,           4),
        0x5E => (LSR, AbsoluteX,           7),
        0x5F => (EOR, AbsoluteLongX,       5),
        0x60 => (RTS, Stack,               6),
        0x61 => (ADC, DirectIndirectX,     6),
        0x62 => (PER, ImmediateWord,       6),
        0x63 => (ADC, StackRelative,       4),
        0x64 => (STZ, Direct,              3),
        0x65 => (ADC, Direct,              3),
        0x66 => (ROR, Direct,              5),
        0x67 => (ADC, DirectIndirectLong,  6),
        0x68 => (PLA, Stack,               4),
        0x69 => (ADC, ImmediateAcc,        2),
        0x6A => (ROR, ImmediateAcc,        2),
        0x6B => (RTL, Stack,               6),
        0x6C => (JMP, AbsoluteIndirect,    5),
        0x6D => (ADC, Absolute,            4),
        0x6E => (ROR, Absolute,            6),
        0x6F => (ADC, AbsoluteLong,        5),
        0x70 => (BVS, Relative,            2),
        0x71 => (ADC, DirectIndirectY,     5),
        0x72 => (ADC, DirectIndirect,      5),
        0x73 => (ADC, StackRelativeY,      7),
        0x74 => (STZ, DirectX,             4),
        0x75 => (ADC, DirectX,             4),
        0x76 => (ROR, DirectX,             6),
        0x77 => (ADC, DirectIndirectLongY, 6),
        0x78 => (SEI, Implied,             2),
        0x79 => (ADC, AbsoluteY,           4),
        0x7A => (PLY, Stack,               4),
        0x7B => (TDC, Implied,             2),
        0x7C => (JMP, AbsoluteIndirectX,   6),
        0x7D => (ADC, AbsoluteX,           4),
        0x7E => (ROR, AbsoluteX,           7),
        0x7F => (ADC, AbsoluteLongX,       5),
        0x80 => (BRA, Relative,            2),
        0x81 => (STA, DirectIndirectX,     6),
        0x82 => (BRL, RelativeLong,        4),
        0x83 => (STA, StackRelative,       4),
        0x84 => (STY, Direct,              3),
        0x85 => (STA, Direct,              3),
        0x86 => (STX, Direct,              3),
        0x87 => (STA, DirectIndirectLong,  2),
        0x88 => (DEY, Implied,             2),
        0x89 => (BIT, ImmediateAcc,        2),
        0x8A => (TXA, Implied,             2),
        0x8B => (PHB, Stack,               3),
        0x8C => (STY, Absolute,            4),
        0x8D => (STA, Absolute,            4),
        0x8E => (STX, Absolute,            4),
        0x8F => (STA, AbsoluteLong,        5),
        0x90 => (BCC, Relative,            2),
        0x91 => (STA, DirectIndirectY,     6),
        0x92 => (STA, DirectIndirect,      5),
        0x93 => (STA, StackRelativeY,      7),
        0x94 => (STY, DirectX,             4),
        0x95 => (STA, DirectX,             4),
        0x96 => (STX, DirectY,             4),
        0x97 => (STA, DirectIndirectLongY, 6),
        0x98 => (TYA, Implied,             2),
        0x99 => (STA, AbsoluteY,           5),
        0x9A => (TXS, Implied,             2),
        0x9B => (TXY, Implied,             2),
        0x9C => (STZ, Absolute,            4),
        0x9D => (STA, AbsoluteX,           5),
        0x9E => (STZ, AbsoluteX,           5),
        0x9F => (STA, AbsoluteLongX,       5),
        0xA0 => (LDY, ImmediateIdx,        2),
        0xA1 => (LDA, DirectIndirectX,     6),
        0xA2 => (LDX, ImmediateIdx,        2),
        0xA3 => (LDA, StackRelative,       4),
        0xA4 => (LDY, Direct,              3),
        0xA5 => (LDA, Direct,              3),
        0xA6 => (LDX, Direct,              3),
        0xA7 => (LDA, DirectIndirectLong,  3),
        0xA8 => (TAY, Implied,             2),
        0xA9 => (LDA, ImmediateAcc,        2),
        0xAA => (TAX, Implied,             2),
        0xAB => (PLB, Stack,               4),
        0xAC => (LDY, Absolute,            4),
        0xAD => (LDA, Absolute,            4),
        0xAE => (LDX, Absolute,            4),
        0xAF => (LDA, AbsoluteLong,        5),
        0xB0 => (BCS, Relative,            2),
        0xB1 => (LDA, DirectIndirectY,     5),
        0xB2 => (LDA, DirectIndirect,      5),
        0xB3 => (LDA, StackRelativeY,      7),
        0xB4 => (LDY, DirectX,             4),
        0xB5 => (LDA, DirectX,             4),
        0xB6 => (LDX, DirectY,             4),
        0xB7 => (LDA, DirectIndirectLongY, 6),
        0xB8 => (CLV, Implied,             2),
        0xB9 => (LDA, AbsoluteY,           4),
        0xBA => (TSX, Implied,             2),
        0xBB => (TYX, Implied,             2),
        0xBC => (LDY, AbsoluteX,           4),
        0xBD => (LDA, AbsoluteX,           4),
        0xBE => (LDX, AbsoluteY,           4),
        0xBF => (LDA, AbsoluteLongX,       5),
        0xC0 => (CPY, ImmediateIdx,        2),
        0xC1 => (CMP, DirectIndirectX,     6),
        0xC2 => (REP, ImmediateByte,       3),
        0xC3 => (CMP, StackRelative,       4),
        0xC4 => (CPY, Direct,              3),
        0xC5 => (CMP, Direct,              3),
        0xC6 => (DEC, Direct,              5),
        0xC7 => (CMP, DirectIndirectLong,  6),
        0xC8 => (INY, Implied,             2),
        0xC9 => (CMP, ImmediateAcc,        2),
        0xCA => (DEX, Implied,             2),
        0xCB => (WAI, Implied,             3),
        0xCC => (CPY, Absolute,            4),
        0xCD => (CMP, Absolute,            4),
        0xCE => (DEC, Absolute,            6),
        0xCF => (CMP, AbsoluteLong,        5),
        0xD0 => (BNE, Relative,            2),
        0xD1 => (CMP, DirectIndirectY,     5),
        0xD2 => (CMP, DirectIndirect,      5),
        0xD3 => (CMP, StackRelativeY,      7),
        0xD4 => (PEI, Direct,               6),
        0xD5 => (CMP, DirectX,             4),
        0xD6 => (DEC, DirectX,             6),
        0xD7 => (CMP, DirectIndirectLongY, 6),
        0xD8 => (CLD, Implied,             2),
        0xD9 => (CMP, AbsoluteY,           4),
        0xDA => (PHX, Stack,               3),
        0xDB => (STP, Implied,             3),
        0xDC => (JML, AbsoluteIndirect,    6),
        0xDD => (CMP, AbsoluteX,           4),
        0xDE => (DEC, AbsoluteX,           7),
        0xDF => (CMP, AbsoluteLongX,       5),
        0xE0 => (CPX, ImmediateIdx,        2),
        0xE1 => (SBC, DirectIndirectX,     6),
        0xE2 => (SEP, ImmediateByte,       3),
        0xE3 => (SBC, StackRelative,       4),
        0xE4 => (CPX, Direct,              3),
        0xE5 => (SBC, Direct,              3),
        0xE6 => (INC, Direct,              5),
        0xE7 => (SBC, DirectIndirectLong,  6),
        0xE8 => (INX, Implied,             2),
        0xE9 => (SBC, ImmediateAcc,        2),
        0xEA => (NOP, Implied,             2),
        0xEB => (XBA, Implied,             3),
        0xEC => (CPX, Absolute,            4),
        0xED => (SBC, Absolute,            4),
        0xEE => (INC, Absolute,            6),
        0xEF => (SBC, AbsoluteLong,        5),
        0xF0 => (BEQ, Relative,            2),
        0xF1 => (SBC, DirectIndirectY,     5),
        0xF2 => (SBC, DirectIndirect,      5),
        0xF3 => (SBC, StackRelativeY,      7),
        0xF4 => (PEA, ImmediateWord,       5),
        0xF5 => (SBC, DirectX,             4),
        0xF6 => (INC, DirectX,             6),
        0xF7 => (SBC, DirectIndirectLongY, 6),
        0xF8 => (SED, Implied,             2),
        0xF9 => (SBC, AbsoluteY,           4),
        0xFA => (PLX, Stack,               4),
        0xFB => (XCE, Implied,             2),
        0xFC => (JSR, AbsoluteIndirectX,   8),
        0xFD => (SBC, AbsoluteX,           4),
        0xFE => (INC, AbsoluteX,           7),
        0xFF => (SBC, AbsoluteLongX,       5),
    );
